import Head from "next/head";
import React from "react";
import styles from "../styles/layout.module.css";
import Menu from "./menu";
import ShoppingCard from "./shopping-card";

const Layout = ({ children, title }) => {
  return (
    <div>
      <Head>
        <title>Github Merch {title ? `| ${title}` : ""}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <div className={styles.container}>{children}</div>
      <ShoppingCard />
    </div>
  );
};

export default Layout;
